create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  status text not null default 'pending',
  priority text not null default 'normal',
  reminder_at timestamptz,
  due_at timestamptz,
  category text not null default 'Personal',
  subtasks jsonb not null default '[]'::jsonb,
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.todos enable row level security;

create policy "Users can read their todos"
on public.todos for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert todos"
on public.todos for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update todos"
on public.todos for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete todos"
on public.todos for delete
to authenticated
using (auth.uid() = user_id);
